"""Handler: auditd configuration & tampering. Output: auditd_config.csv

Reads /etc/audit on a host that has auditd installed and reports three things:

- coverage: how much the loaded ruleset (audit.rules, generated by augenrules)
  actually audits -- watch (-w) and syscall (-a ...always/exit -S) rule counts,
  whether `-a task,never` suppresses all syscall auditing, and the -e enable
  state. Informational: a `task,never`/no-rules posture is the stock default on
  several distros (notably SUSE), so it is surfaced, not flagged -- except when
  the loaded ruleset itself carries `-e 0` (auditing explicitly turned off).
- daemon: auditd.conf settings that weaken logging -> flagged. write_logs=no,
  flush=none, max_log_file_action=ignore, log_format=nolog, or a non-default
  log_file all reduce what survives on disk (anti-forensics).
- tampering: rules present in the previously-loaded ruleset (audit.rules.prev)
  but gone from the loaded audit.rules -> flagged (someone stopped auditing a
  path/syscall). Rules that were added are surfaced, not flagged.

Self-gates (HandlerSkip) when /etc/audit is absent.
"""

from __future__ import annotations

from artifact_engine.core.runner import HandlerSkip
from artifact_engine.handlers._lincommon import read_lines, root, write_csv

_DEFAULT_LOG = "/var/log/audit/audit.log"


def _rule_lines(lines: list[str]) -> list[str]:
    """Non-comment, non-blank rule lines, whitespace-normalised."""
    out = []
    for ln in lines:
        s = " ".join(ln.split())
        if s and not s.startswith("#"):
            out.append(s)
    return out


def _coverage_rules(rules: list[str]) -> set[str]:
    """The subset that constitutes actual audit coverage: file watches (-w) and
    syscall rules (-a always/exit). Excludes -D, buffer tuning and the
    `-a task,never` suppression (those aren't coverage)."""
    cov = set()
    for r in rules:
        low = r.lower()
        if low.startswith("-w "):
            cov.add(r)
        elif low.startswith("-a ") and ("always" in low or "exit" in low) and "never" not in low:
            cov.add(r)
    return cov


def _enable_state(rules: list[str]) -> str | None:
    """Last `-e N` in the loaded ruleset, or None if unset (defaults enabled)."""
    state = None
    for r in rules:
        toks = r.split()
        if len(toks) >= 2 and toks[0] == "-e":
            state = toks[1]
    return state


def _conf(lines: list[str]) -> dict[str, str]:
    cfg = {}
    for ln in lines:
        s = ln.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, _, v = s.partition("=")
        cfg[k.strip().lower()] = v.strip()
    return cfg


def run(ctx) -> None:
    audit = root(ctx.evidence) / "etc" / "audit"
    if not audit.is_dir():
        raise HandlerSkip("no /etc/audit (auditd not installed)")

    rows: list[list] = []

    loaded = _rule_lines(read_lines(audit / "audit.rules"))
    cov = _coverage_rules(loaded)
    has_never = any("task,never" in r.lower() or "never,task" in r.lower() for r in loaded)
    nwatch = sum(1 for r in cov if r.lower().startswith("-w "))
    nsys = len(cov) - nwatch
    e = _enable_state(loaded)
    disabled = e == "0"
    detail = (f"{nwatch} watch + {nsys} syscall rule(s); "
              f"task,never={'yes' if has_never else 'no'}; "
              f"enabled=-e{e if e is not None else '?'}")
    if (nwatch + nsys) == 0 and not disabled:
        detail += " [no syscall auditing]"
    rows.append(["coverage", detail, "yes" if disabled else "no"])

    # auditd.conf: settings that reduce what reaches disk.
    cfg = _conf(read_lines(audit / "auditd.conf"))
    if cfg:
        bad = []
        if cfg.get("write_logs", "yes").lower() == "no":
            bad.append("write_logs=no")
        if cfg.get("flush", "").lower() == "none":
            bad.append("flush=none")
        if cfg.get("max_log_file_action", "").lower() == "ignore":
            bad.append("max_log_file_action=ignore")
        if cfg.get("log_format", "").lower() == "nolog":
            bad.append("log_format=nolog")
        log_file = cfg.get("log_file", _DEFAULT_LOG)
        if log_file and log_file != _DEFAULT_LOG:
            bad.append(f"log_file={log_file}")
        summary = (f"write_logs={cfg.get('write_logs', '?')}; "
                   f"max_log_file_action={cfg.get('max_log_file_action', '?')}; "
                   f"log_file={log_file}")
        if bad:
            summary += " [" + ", ".join(bad) + "]"
        rows.append(["daemon", summary, "yes" if bad else "no"])

    # Tampering: rules dropped since the previous loaded ruleset.
    prev_path = audit / "audit.rules.prev"
    if prev_path.is_file():
        prev_cov = _coverage_rules(_rule_lines(read_lines(prev_path)))
        for r in sorted(prev_cov - cov):
            rows.append(["rule_removed", r, "yes"])
        for r in sorted(cov - prev_cov):
            rows.append(["rule_added", r, "no"])

    write_csv(ctx.out, "auditd_config.csv", ["kind", "detail", "suspicious"], rows)
